// <auto-generated />
namespace CaptureClients.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CustomersFieldChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomersFieldChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201805311729574_CustomersFieldChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
